<?php

/**
 * @file
 * On behalf implementation of Feeds mapping API for domain_feeds.module.
 */

/**
 * Implementation of hook_feeds_processor_targets_alter().
 *
 * @see FeedsNodeProcessor::getMappingTargets().
 */
function domain_feeds_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  $options = array();
  // Get the display format of the form element.
  $format = domain_select_format();
  foreach (domain_domains() as $data) {
    // Cannot pass zero in checkboxes.
    $key = ($data['domain_id'] == 0) ? -1 : $data['domain_id'];
    // The domain must be valid.
    if ($data['valid'] || user_access('access inactive domains')) {
      // Checkboxes must be filtered, select lists should not.
      $targets['domains:'. $key] = array(
        'name' => 'Publish to: '. (empty($format) ? check_plain($data['sitename']) : $data['sitename']),
        'callback' => 'domain_feeds_set_target',
        'description' => t('Domain access options.'),
      );
    }
  }

  $targets['domains:multiple'] = array(
    'name' => 'Publish to (multiple)',
    'callback' => 'domain_feeds_set_target_multiple',
    'description' => t('Domain access options.'),
  );

  // Publish to All
  $targets['domains:all'] = array(
    'name' => 'Publish to: All',
    'callback' => 'domain_feeds_set_target_all',
    'description' => t('Domain access options.'),
  );
}

/**
 * Callback for mapping. Here is where the actual mapping happens.
 *
 * When the callback is invoked, $target contains the name of the field the
 * user has decided to map to and $value contains the value of the feed item
 * element the user has picked as a source.
 */
function domain_feeds_set_target($source, $entity, $target, $feed_element) {
  list($target, $sub_field) = explode(':', $target);
  $field = !empty($entity->$target) ? $entity->$target : array();
  
  if ($sub_field === -1 && $feed_element) {
    $field[$sub_field] = -1;
  } 
  else if ($feed_element) {
    $field[$sub_field] = $sub_field;
  }

  if (count($field)) {
    $entity->$target = $field;
    $entity->domain_site = 0;
  }

  return $entity;
}

/**
 * @param $source
 * @param $entity
 * @param $target
 * @param array $values
 *   The domain IDs.
 * @param $mapping
 */
function domain_feeds_set_target_multiple($source, $entity, $target, $value, $mapping) {
  $values = explode(',', $value);
  list($target, $sub_field) = explode(':', $target);
  foreach (domain_id_list() as $domain_id) {
    $value = in_array($domain_id, $values) ? '1' : '0';
    $key = ($domain_id == 0) ? -1 : $domain_id;
    domain_feeds_set_target($source, $entity, $target . ':' . $key, $value, $mapping);
  }
}

/**
 * Callback for mapping. Here is where the actual mapping happens.
 * 
 * When the callback is invoked, $target contains the name of the field the
 * user has decided to map to and $value contains the value of the feed item
 * element the user has picked as a source.
 */
function domain_feeds_set_target_all($source, $entity, $target, $feed_element) {
  $entity->domain_site = 1;
  $entity->domain_source = 0;
  
  return $entity;
}
